### ISSUE TITLE
反馈一个问题

### ISSUE THREAD

**Issue by yihanxx** [Mrzqd/Bncr_pulgins#1]
Openwrt重启wan口重播以后，发送给频道的消息无法被bncr接收，不知有何好方法解决。目前采取拨号重启bncr的方案。

**Comment by Mrzqd** [comment]
频道bot重连机制有问题，目前无法解决

**Comment by yihanxx** [comment]
好的 感谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mrzqd ***@***.***&gt;
发送时间: 2023年7月29日 09:12
收件人: Mrzqd/Bncr_pulgins ***@***.***&gt;
抄送: yihanxx ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Mrzqd/Bncr_pulgins] 反馈一个问题 (Issue #1)





 
频道bot重连机制有问题，目前无法解决
